- Updated requirements.txt and requirements-unlocked.txt - Linting - selenium_test/test.py   - Linting   - Refactoring   - Documentation   - Added chromedriver binaries
Stuck on bug:
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home